# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: scanstock-secrets
type: Opaque
data:
  # Values are base64 encoded
  DB_PASSWORD: ckhlNEUwS3VRSmYyZlFDNQ==  # rHe4E0KuQJf2fQC5
  JWT_SECRET: WDA3RHhPYWQ0MDVMZjZoRzN2Z0FqcCtLdStvOWo3Rkk5cWFmc0xqallqMD0=
  SUPABASE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5OcFpuQnliWE50YkdKdlpIUnJjMlptYUcxdUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRFek5EWTVPRElzSW1WNGNDSTZNakExTmpreU1qazRNbjAuemhIdTN3emxULUh0WHZuNXRrWDRERVRRczJxNW1jOFUwYjZZTlpWbkI4az0=
  SUPABASE_SERVICE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5OcFpuQnliWE50YkdKdlpIUnJjMlptYUcxdUlpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMwTVRNME5qazRNaXdpWlhod0lqb3lNRFUyT1RJeU9UZ3lmUS5Ub2lqT1dlLTNNeVNzQ01wdmY4S2F3aE5tTzZXT2UySGJSNlItLUxUWVFn
  JWT_EXPIRATION: MWQ=  # 1d
