apiVersion: v1
kind: Service
metadata:
  name: scanstock-api-service
spec:
  selector:
    app: scanstock-api
  ports:
    - protocol: TCP 
      port: 3000
  type: LoadBalancer  # Change to LoadBalancer or NodePort if needed